### ISSUE TITLE
Error in estim_expr[[gs]] <- NA 

### ISSUE THREAD

**Issue by mimisikai** [borishejblum/TcGSA#12]
Hi Boris,

When I'm applying your tool to my data, I encounter such problem:

```R
tcgsa_kegg <- TcGSA.LR(expr = Expr_timecourseDEG, gmt = GS_kegg_symbols, design=VAC_design_info, subject_name="SampleID", time_name="TimePoint4",time_func="linear", crossedRandom=FALSE)
```
```
The size of the gene set  is problematic (too many or too few genes)
1/0 gene sets analyzed
Error in estim_expr[[gs]] <- NA : 
  attempt to select less than one element in integerOneIndex

The Expr as:
head(Expr_timecourseDEG)
             VX2012001-1 VX2012001-2 VX2012001-3 VX2012001-4 VX2012001-5 VX2012001-6 VX2012001-7 VX2012001-8
TMEM170B        9.182150   10.010291    8.291170    8.294945    8.670463    8.968038    9.332901    8.857322
LRRC70          7.071383    5.815093    7.490385    5.639441    6.237027    5.315666    5.200694    6.044537
LOC100131223    6.782041    6.715671    6.532948    6.446217    6.602485    6.997213    6.871205    6.193584
SCARNA9L        4.027434    4.025486    3.629000    4.425038    3.592312    4.530262    4.006157    4.117338
LOC100287896    4.697225    5.152030    5.466629    5.336391    5.170701    5.464558    5.453087    5.400047
LOC100421281    5.704890    5.945343    5.428337    5.804572    5.904961    5.799740    5.841419    5.111985
```
design file is VAC_design_info:
```R
head(VAC_design_info)
```
```
                  FileNames    SampleID SubjectID TimePoint1 TimePoint2 TimePoint3 TimePoint4 Group  Scheme
VX2012001-1 VX2012001-1.CEL VX2012001-1 VX2012001       Day0      Day 0       Day0        0.0    G1 Vaccine
VX2012001-2 VX2012001-2.CEL VX2012001-2 VX2012001      Hour4     Hour 4     Day0.2        0.2    G2 Vaccine
VX2012001-3 VX2012001-3.CEL VX2012001-3 VX2012001       Day1      Day 1       Day1        1.0    G3 Vaccine
VX2012001-4 VX2012001-4.CEL VX2012001-4 VX2012001       Day3      Day 3       Day3        3.0    G4 Vaccine
VX2012001-5 VX2012001-5.CEL VX2012001-5 VX2012001       Day7      Day 7       Day7        7.0    G5 Vaccine
VX2012001-6 VX2012001-6.CEL VX2012001-6 VX2012001       Day9      Day 9       Day9        9.0    G6 Vaccine
```

The column "TimePoint4" is numeric variable, which has been used in the TcGSA.LR. 
The gmt file also load as Gene Symbol format.

**Comment by borishejblum** [comment]
Hi again Jue,

From what it seems, there could be gene sets from `GS_kegg_symbols` for which 0 genes are measured in your data `Expr_timecourseDEG`.

Again, it would be helpful if you could provide a reproducible example for the error. This would help me diagnose the error, and meka TcGSA more robbust to it.

Thanks a lot,
Boris

**Comment by mimisikai** [comment]
Hi Boris,

 

Thank you so much for your responses. I attach my .Rdata here for your troubleshooting. Please keep the data in confidential and delete then after when you finish the test. Thank you. 

 

Here the codes:

 

Firstly, I generate the gmt data from gmt file:

GS_all_entrez <- read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/msigdb.v6.0.entrez.gmt")

GS_go_entrez <- read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c5.all.v6.0.entrez.gmt")

GS_hall_entrez <- read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/h.all.v6.0.entrez.gmt")

GS_kegg_entrez <- read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c2.cp.kegg.v6.0.entrez.gmt")

GS_biocarta_entrez <- read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c2.cp.biocarta.v6.0.entrez.gmt")

GS_reactome_entrez <- read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c2.cp.reactome.v6.0.entrez.gmt")

 

GS_all_symbols <- read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/msigdb.v6.0.symbols.gmt")

GS_go_symbols <- read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c5.all.v6.0.symbols.gmt")

GS_hall_symbols <- read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/h.all.v6.0.symbols.gmt")

GS_kegg_symbols <- read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c2.cp.kegg.v6.0.symbols.gmt")

GS_biocarta_symbols <- read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c2.cp.biocarta.v6.0.symbols.gmt")

GS_reactome_symbols <- read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c2.cp.reactome.v6.0.symbols.gmt")

 

save(GS_all_entrez,GS_go_entrez,GS_hall_entrez,GS_kegg_entrez,GS_biocarta_entrez,GS_reactome_entrez,

     GS_all_symbols,GS_go_symbols,GS_hall_symbols,GS_kegg_symbols,GS_biocarta_symbols,GS_reactome_symbols,

     file = "/Users/juehou/Documents/Microarray Data/gmt database version6/GeneSet_gmt.Rdata")

 

Then, 

load("Expr_timecourseDEG.RData")

load("VAC_design_info.Rdata")

 

# remane the Expr colname to match with sample ID

colnames(Expr_timecourseDEG) = VAC_design_info$SampleID 

 

# run the script with time point

tcgsa_kegg <- TcGSA.LR(expr = Expr_timecourseDEG, gmt = GS_go_symbols, design=VAC_design_info, 

                       subject_name="SampleID", time_name="TimePoint4",

time_func="linear", crossedRandom=FALSE)

**Comment by mimisikai** [comment]
Hi again Boris,

 

Sorry for the mistake in the previous email. I misused another function to read gmt file. Here the correct one, but I face the problem when I plot the result. I don’t sure if the numeric time point has been recognized well. Please take a look. Thank you. –Jue

 

TCGSA_all_entrez <- GSA.read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/msigdb.v6.0.entrez.gmt")

TCGSA_go_entrez <- GSA.read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c5.all.v6.0.entrez.gmt")

TCGSA_hall_entrez <- GSA.read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/h.all.v6.0.entrez.gmt")

TCGSA_kegg_entrez <- GSA.read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c2.cp.kegg.v6.0.entrez.gmt")

TCGSA_biocarta_entrez <- GSA.read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c2.cp.biocarta.v6.0.entrez.gmt")

TCGSA_reactome_entrez <- GSA.read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c2.cp.reactome.v6.0.entrez.gmt")

 

TCGSA_all_symbols <- GSA.read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/msigdb.v6.0.symbols.gmt")

TCGSA_go_symbols <- GSA.read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c5.all.v6.0.symbols.gmt")

TCGSA_hall_symbols <- GSA.read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/h.all.v6.0.symbols.gmt")

TCGSA_kegg_symbols <- GSA.read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c2.cp.kegg.v6.0.symbols.gmt")

TCGSA_biocarta_symbols <- GSA.read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c2.cp.biocarta.v6.0.symbols.gmt")

TCGSA_reactome_symbols <- GSA.read.gmt("/Users/juehou/Documents/Microarray Data/gmt database version6/c2.cp.reactome.v6.0.symbols.gmt")

 

# remane the Expr colname to match with sample ID

colnames(Expr_timecourseDEG) = VAC_design_info$SampleID 

 

# run the script with time point

tcgsa_kegg <- TcGSA.LR(expr = Expr_timecourseDEG, gmt = TCGSA_kegg_symbols, design=VAC_design_info, 

                       subject_name="SampleID", time_name="TimePoint4",

                       time_func="linear", crossedRandom=FALSE)

summary(tcgsa_sim_1grp)

 

                                A TcGSA object

Form of the time trend:

                linear

Number of treatment groups:

                1

Number of gene sets tested for significant time trend:

                186

 

Number of significant gene sets at a 5% threshold (BY procedure):

                0 out of 186 gene sets

 

 

# Plot the results

pdf("Time-Course Gene Set Analysis-KEGG.pdf")

  plot(x = tcgsa_kegg, expr = tcgsa_kegg$Estimations, 

       Subject_ID = VAC_design_info$Patient_ID, TimePoint = VAC_design_info$TimePoint4,

       baseline = 0.0, B=100, time_unit="H",

       dendrogram.size = 0.4, heatmap.width = 0.8, heatmap.height = 2, cex.main = 0.7)

dev.off()

 

Error in plot.TcGSA(x = tcgsa_kegg, expr = tcgsa_kegg$Estimations, Subject_ID = VAC_design_info$Patient_ID,  : 

  The 'baseline' value used is not one of the time points in 'TimePoint'...

**Comment by mimisikai** [comment]
Should be 

> plot(x = tcgsa_kegg, expr = tcgsa_kegg$Estimations, 

+        Subject_ID = VAC_design_info$SampleID, TimePoint = VAC_design_info$TimePoint4,

+        baseline = 0.0, B=100, time_unit="H",

+        dendrogram.size = 0.4, heatmap.width = 0.8, heatmap.height = 2, cex.main = 0.7)

Error in plot.TcGSA(x = tcgsa_kegg, expr = tcgsa_kegg$Estimations, Subject_ID = VAC_design_info$SampleID,  : 

  The 'baseline' value used is not one of the time points in 'TimePoint'...

**Comment by borishejblum** [comment]
Hi Jue,

It seems you did not realized your emails are posted directly on GitHub, without the attachments. So I did not get your .RData files and cannot test your code. Please respond directly on GitHub, and you can send me your files by email directly at my **institutional email address**.

Boris

**Comment by mimisikai** [comment]
Thank you, Boris. The problem is describing  here. 

# read gmt file
all_symbols <- GSA.read.gmt("../msigdb.v6.0.symbols.gmt")

# remane the Expr colname to match with sample ID 
colnames(Expr_timecourseDEG) = VAC_design_info$SampleID 

# run the script with time point 
tcgsa_kegg <- TcGSA.LR(expr = Expr_timecourseDEG, gmt = all_symbols, 
design=VAC_design_info, subject_name="SampleID", time_name="TimePoint4",time_func="linear", crossedRandom=FALSE) 

summary(tcgsa_kegg)

# plot figure
 plot(x = tcgsa_kegg, expr = tcgsa_kegg$Estimations,
+        Subject_ID = VAC_design_info$SampleID, TimePoint = VAC_design_info$TimePoint4,
+        baseline = 0.0, B=100, time_unit="H",
+        dendrogram.size = 0.4, heatmap.width = 0.8, heatmap.height = 2, cex.main = 0.7)

Error in plot.TcGSA(x = tcgsa_kegg, expr = tcgsa_kegg$Estimations, Subject_ID = VAC_design_info$SampleID,  :   The 'baseline' value used is not one of the time points in 'TimePoint'...

I send you Rdata file to your personal emailbox.

**Comment by borishejblum** [comment]
Hi Jue,

So the ploting error was due to the fact that you are testing a lot of genesets for which no genes was measured in your expression matrix, including the first geneset investigated. I improved the way this is handled and the following command should produce the expected plot:
```R
plot(x = tcgsa_kegg, 
     expr = tcgsa_kegg$Estimations, 
     Subject_ID = VAC_design_info$SampleID, 
     TimePoint = VAC_design_info$TimePoint4,  
     B=100, 
     baseline = 0,
     time_unit="Day ",
     descript = FALSE,
     dendrogram.size = 0.4, 
     heatmap.width = 0.8, 
     heatmap.height = 2, 
     cex.main = 0.7)
```

I also fixed the name display of the genesets. You can install the latest version of the package that contains the fix with the following command:
```R 
devtools::install_github("borishejblum/TcGSA")
```
Let me know if you still encounter problems.

Boris

**Comment by mimisikai** [comment]
Thank you so much, Boris!

**Comment by mimisikai** [comment]
Hi Boris,

 

I still stick on the error. I don’t run the all.gmt geneset, there’re more than 11,000 geneset, my laptop cannot handle these huge data. But I use KEGG(c2.cp.kegg.v6.0.symbols.gmt) or reactome (c2.cp.reactome.v6.0.symbols.gmt) pathway data, in the summary, I can see, 

 

For Reactome pathway,  30 out of 674 gene sets;

                                

A TcGSA object

Form of the time trend:

                linear

Number of treatment groups:

                1

Number of gene sets tested for significant time trend:

                674

 

Number of significant gene sets at a 5% threshold (BY procedure):

                30 out of 674 gene sets

 

And for KEGG pathway, 14 out of 186 gene sets;

 

                                A TcGSA object

Form of the time trend:

                linear

Number of treatment groups:

                1

Number of gene sets tested for significant time trend:

                186

 

Number of significant gene sets at a 5% threshold (BY procedure):

                14 out of 186 gene sets

 

That means my gene have been matched to the geneset. However, I still get the error code when I plot it:

 

Error in plot.TcGSA(x = tcgsa_go, expr = tcgsa_go$Estimations, Subject_ID = VAC_design_info$SampleID,  : 

  The 'baseline' value used is not one of the time points in 'TimePoint'...

 

Is the problem of the time point data? I’m really confused. 

 

Thank you.

 

Jue

**Comment by borishejblum** [comment]
Hi Jue,

Again, I need the command (code) taht gives you the error in order to track it down. Can you provide the exact code that still gives the error ?

Thanks,
Boris

**Comment by mimisikai** [comment]
# remane the Expr colname to match with sample ID

colnames(Expr_timecourseDEG) = VAC_design_info$SampleID 

 

# run the script with time point

tcgsa <- TcGSA.LR(expr = Expr_timecourseDEG, gmt = TCGSA_kegg_symbols, design = VAC_design_info, 

                      subject_name="SampleID", time_name = "TimePoint4",time_func = "linear", crossedRandom = FALSE)

summary(tcgsa)

 

# in the TcGSA.LR function, the gmt is either KEGG(c2.cp.kegg.v6.0.symbols.gmt) or reactome (c2.cp.reactome.v6.0.symbols.gmt).

# For KEGG, should have Number of significant gene sets at a 5% threshold (BY procedure):

                14 out of 186 gene sets

# For reactome, should have Number of significant gene sets at a 5% threshold (BY procedure):

                30 out of 674 gene sets

 

 

# Plot the results

plot(x = tcgsa, expr = tcgsa $Estimations, 

       Subject_ID = VAC_design_info$SampleID, TimePoint = VAC_design_info$TimePoint4,

       baseline = 0, B = 100, time_unit = "Day ",descript = FALSE,

       dendrogram.size = 0.4, heatmap.width = 0.8, heatmap.height = 2, cex.main = 0.7)

 

You can still use the .Rdata files that I sent to you.

**Comment by borishejblum** [comment]
Hi Jue,

So everything works fine on my computer, and I don't get any error... 
Did you re-install the TcGSA package since yesterday ? You need to, in order to not have the error anymore. I uploaded the new version to the CRAN last night).

Below is the entire code I am running successfully (and that should work on your computer):

```R
rm(list=ls())
install.packages("TcGSA", type = 'source')

library(TcGSA)
load("Expr_timecourseDEG.RData")
load("VAC_design_info.Rdata")
TCGSA_kegg_symbols <- GSA::GSA.read.gmt("c2.cp.kegg.v6.0.symbols.gmt")
TCGSA_reactome_symbols <- GSA::GSA.read.gmt("c2.cp.reactome.v6.0.symbols.gmt")

# rename the Expr colname to match with sample ID
colnames(Expr_timecourseDEG) <-  VAC_design_info$SampleID

# KEGG
tcgsa_kegg_res <- TcGSA.LR(expr = Expr_timecourseDEG, 
						   gmt = TCGSA_kegg_symbols, 
						   design = VAC_design_info, 
						   subject_name = "SampleID", 
						   time_name = "TimePoint4",
						   time_func = "linear", 
						   crossedRandom = FALSE)
summary(tcgsa_kegg_res)
plot(x = tcgsa_kegg_res, 
	 expr = tcgsa_kegg_res$Estimations, 
	 Subject_ID = VAC_design_info$SampleID, 
	 TimePoint = VAC_design_info$TimePoint4, 
	 baseline = 0, 
	 B = 100, 
	 time_unit = "Day ",
	 descript = FALSE, 
	 dendrogram.size = 0.4, 
	 heatmap.width = 0.8, 
	 heatmap.height = 2, 
	 cex.main = 0.7)

# REACTOME
tcgsa_reactome_res <- TcGSA.LR(expr = Expr_timecourseDEG, 
						   gmt = TCGSA_reactome_symbols, 
						   design = VAC_design_info, 
						   subject_name = "SampleID", 
						   time_name = "TimePoint4",
						   time_func = "linear", 
						   crossedRandom = FALSE)
summary(tcgsa_reactome_res)
plot(x = tcgsa_reactome_res, 
	 expr = tcgsa_reactome_res$Estimations, 
	 Subject_ID = VAC_design_info$SampleID, 
	 TimePoint = VAC_design_info$TimePoint4, 
	 baseline = 0, 
	 B = 100, 
	 time_unit = "Day ",
	 descript = FALSE, 
	 dendrogram.size = 0.4, 
	 heatmap.width = 0.8, 
	 heatmap.height = 2, 
	 cex.main = 0.7)
```

Best,
Boris
