### ISSUE TITLE
Vignette yet?

### ISSUE THREAD

**Issue by mebbert** [borishejblum/TcGSA#13]
Hi Boris,

Just curious if you've started on a vignette, yet. It would be super helpful. Thanks!

**Comment by borishejblum** [comment]
Hi Mark, 

Making a vignette is on my to-do list, sadly I haven't yet found enough time to write something useful. If you are interested I recommend you take a look at the reproducible R script from the TcGSA paper available here :
[https://doi.org/10.1371/journal.pcbi.1004310.s007](https://doi.org/10.1371/journal.pcbi.1004310.s007)

Boris

**Comment by borishejblum** [comment]
We have finally added a vignette.
