### ISSUE TITLE
Unknown or uninitialised column: 'geneset.names'.

### ISSUE THREAD

**Issue by elcega** [borishejblum/TcGSA#19]
I have created the three gene expression matrix (gem), design data matrix (ddm) and gmt.

```
> head(gem)
             S1           S2           S3           S4           S5           S6
A1 0.0006931562 0.0006773538 0.0007278626 6.508220e-04 9.083433e-04 1.126689e-03
A2 0.0019153881 0.0019366267 0.0014765212 1.573681e-03 2.584282e-03 7.389090e-03
...


> head(gmt_gmt)
# A tibble: 3 x 94
  GeneSet Description ...3  ...4  ...5  ...6  ...7  ...8  ...9  ...10 ...11 ...12 ...13
  <chr>   <chr>       <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr>
1 AA      Up_mid      A1    A2    A3    A4    A5    A6    A7    A8    A9    A10   A11  
2 BB      Up_west     B1    B2    B3    B4    B5    B6    B7    B8    B9    B10   B11  
3 CC      Up_east     C1    C2    C3    C4    C5    C6    C7    C8    C9    C10   C11 


> head(ddm)
# A tibble: 6 x 3
  Sample Location Station
  <chr>  <chr>      <dbl>
1 S1     West           1
2 S2     West           1
3 S3     West           2
```

> > identical(ncol(gem), nrow(ddm))
> #> [1] TRUE

I have run the following:

```
TcGSA::plot1GS(expr = gem, 
               #plot1GS(expr = tcgsa_result$Estimations,
               gmt = gmt_gmt, 
               Subject_ID = ddm$Location, 
               TimePoint = ddm$Station,
               clustering = FALSE, 
               time_unit = "W", 
               geneset.name = gmt_gmt$GeneSet, 
               title="",
               margins=0.4,
               lab.cex=0.37,
               axis.cex=0.37,
               line.size=0.45,
               gg.add=list(ggplot2::theme(legend.position="none"),
                        ggplot2::ylim(-1.26,1.26)
               ))
```
And obtain the following error

> Unknown or uninitialised column: 'geneset.names'.Error in TcGSA::plot1GS(expr = gem, gmt = gmt_gmt, Subject_ID = ddm$Location,  : 
>   The 'geneset.name' supplied is not in the 'gmt'

How is it possible? I haven't run any likelihood ratio tests and went straight to the graphical outputs (not sure if it matters).

**Comment by elcega** [comment]
I followed steps as shown in here:
https://cran.r-project.org/web/packages/TcGSA/vignettes/TcGSA_userguide.html

**Comment by borishejblum** [comment]
Hi Elena,

Thanks for you interest in our work. 

Unfortunatley, TcGSA is not a visualization tool, it is a statistical method to perform Gene Set Analysis (hence the likelihhod ratios) of **Microarray** gene expression data. 
It has some plotting capapbilities built upon ggplot2, but those are specifically designed to visualize and interpret the output of the statistical method.

Since it seem you do not have microarray data and have solely interested in visualization, I would advize that you turn to visualization software such the `ggplot2` package  itself.

Best,
Boris
