### ISSUE TITLE
Question about coloring and adding legend for individual genes in plot1GS function 

### ISSUE THREAD

**Issue by dzhakparov** [borishejblum/TcGSA#21]
Hello Boris, 

First of all thank you very much for you wonderful package!

I have a basic questions regarding the plots with plot1GS. 

Is it possible to color individual genes in the gene set plot and also add a legend telling what genes are in a depicted gene set? 

Thank you very much in advance.

**Comment by borishejblum** [comment]
Hi,

Thank you for your interest in our work. 

Unfortunately, this option is not supported in plot1GS and I have no plans to develop it in the future. If this is something you would be interested in, you are welcome to propose a pull request implementing that feature.

Best,

**Comment by dzhakparov** [comment]
Thanks a lot for your reply!
